/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.8).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-05-05T17:32:42.805Z[GMT]")
@Api(value = "shutdown", description = "the shutdown API")
public interface ShutdownApi {

    @ApiOperation(value = "Manually trigger a shutdown of this app with a preconfigured delay", nickname = "shutdown", notes = "", response = String.class, tags={ "operations", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Application is shutting down", response = String.class) })
    @RequestMapping(value = "/shutdown",
        produces = { "text/plain" }, 
        method = RequestMethod.GET)
    ResponseEntity<String> shutdown();

}
